CREATE TABLE profiles (
    PROFILEID INT AUTO_INCREMENT PRIMARY KEY,
    USERID INT,
    BIO TEXT NOT NULL,
    IMAGE1 BLOB NOT NULL,
    IMAGE2 BLOB,
    IMAGE3 BLOB,
    OCCUPATION VARCHAR(255) NOT NULL,
    HOBBIES TEXT NOT NULL,
    FOREIGN KEY (USERID) REFERENCES users(Id)
);